Removing retryAfterCount for manual jobs
Expensify/Bedrock pull request #1376
Opened 2022-09-19 23:59 UTC by chiragsalian

### Details

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/220939

### Tests
1. I created two jobs. One manual and another non manual,
```
CreateJob
name: manual/test
retryAfter: +10 minutes
```
```
CreateJob
name: www-prod/test
retryAfter: +10 minutes
```
2. I called GetJobs on them,
```
GetJob
name: manual/test
```
```
GetJob
name: www-prod/test
```
3. I confirmed the manual job did not have its retryAfterCount incremented while the prod job did,
```
sqlite> select * from jobs;
created              jobID                state      name           nextRun              lastRun              repeat  data                   priority  parentJobID  retryAfter
-------------------  -------------------  ---------  -------------  -------------------  -------------------  ------  ---------------------  --------  -----------  -----------
2022-09-19 23:52:31  185975920383287168   RUNQUEUED  manual/test    2022-09-20 00:02:40  2022-09-19 23:52:40          {}                     500       0            +10 minutes
2022-09-19 23:55:33  1689846290350887486  RUNQUEUED  www-prod/test  2022-09-20 00:05:38  2022-09-19 23:55:38          {"retryAfterCount":1}  500       0            +10 minutes
```
_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

2022-09-23 11:50 UTC, flodnv requested changes

2022-09-23 11:50 UTC, flodnv commented on plugins/Jobs.cpp
> +                bool isManualJob = job["name"].rfind("manual", 0) == 0;
Use SStartsWith?

2022-09-23 11:50 UTC, flodnv commented on plugins/Jobs.cpp
> +                                         "nextRun = " + nextRunDateTime + "" +
```suggestion
                                         "nextRun = " + nextRunDateTime +
```

2022-09-26 17:35 UTC, chiragsalian commented
Updated and ready for review.

2022-09-27 14:53 UTC, flodnv approved these changes
Thanks! @tylerkaraszewski can you do a final pass please? 🙏

2022-09-27 17:26 UTC, tylerkaraszewski approved these changes

2022-09-27 17:27 UTC, merged