Add function to get the first of the next month
Expensify/Bedrock pull request #963
Opened 2021-02-23 19:58 UTC by coleaeason

@deetergp this might help you with the thing you're doing in auth. This seems better than passing around a sqlite db object to functions that don't need it only to get the first of the next month.

cc @tylerkaraszewski

2021-02-23 19:58 UTC, coleaeason commented
If you don't need it feel free to close this.

2021-02-23 21:22 UTC, tylerkaraszewski requested changes

2021-02-23 21:22 UTC, tylerkaraszewski commented on libstuff/STime.cpp
> +    t.tm_year = stoull(parts.front()) - 1900;  // This is year - 1900
stoull throws, should catch (below as well)

2021-02-23 21:22 UTC, tylerkaraszewski commented on libstuff/STime.cpp
> +    uint64_t month = stoull(parts.front()) -1;
Pretty sure that months `01` through `09` are going to be interpreted as octal if you don't specify base 10, which is great except for in August and September.

2021-02-23 21:22 UTC, tylerkaraszewski commented on libstuff/STime.cpp
> +string SFirstOfNextMonth(string timeStamp) {
`const string&` param.

2021-02-23 21:22 UTC, tylerkaraszewski commented on libstuff/STime.cpp
> +}
??

2021-02-23 21:22 UTC, tylerkaraszewski commented on test/tests/LibStuffTest.cpp
> +        string timeStamp3 = "2020-06-17";
Add test for August or Sept (possibly octal months) and `"this is not a date"` for catching exceptions.

2021-02-23 22:05 UTC, tylerkaraszewski commented on libstuff/STime.cpp
> +    } catch (const std::invalid_argument& e) {
Annoying, but you don't need `std::`

2021-02-23 22:19 UTC, tylerkaraszewski approved these changes

2021-02-24 01:51 UTC, deetergp commented
Looks good to me!

2021-02-24 01:51 UTC, merged